### ISSUE TITLE
[Feature Request] release workflow

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#1806]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

https://github.com/marvinpinto/action-automatic-releases

### Additional context

demo
```yaml
name: "Github Release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Github Release"
    runs-on: "windows-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/jd-*.zip
```
