### ISSUE TITLE
[Feature Request] Dependency Review Action

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#2059]
### Checklist

- [x] I searched exising issues and no one else requests similar feature.
- [x] I think that 25%+ users are positive towards this feature.

### Describe the feature

https://github.com/actions/dependency-review-action

### Additional context

```yaml
name: 'Dependency Review'
on:
  pull_request:
    paths:
      - '**pom.xml'
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1
```
